config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :cars, only: [:index, :show] do
    resources :reviews, only: [:create]
    resources :favourites, only: [:create]
  end
  resources :favourites, only: [:index, :destroy]

  root "pages#landing"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :owner
  has_many :favourites
  has_many :reviews

  validates :brand, presence: true
  validates :model, presence: true
  validates :year, presence: true, numericality: {only_integer: true}
  validates :fuel, presence: true
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :car

end

app/models/owner.rb
class Owner < ApplicationRecord
  has_many :cars
  validates :nickname, uniqueness: true, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :car

  validates :comment, presence: true, length: { minimum: 6, too_short: "must have at least 6 characters" }
  validates :rating, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.all
  end

  def show
    @car = Car.find(params[:id])
    @review = Review.new

    @favourite = Favourite.new
  end
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController

  def index
    @favourites = Favourite.all
  end

  def create
    @favourite = Favourite.new
    @car = Car.find(params[:car_id])
    @favourite.car = @car

    if @favourite.save
      redirect_to car_path(@car)
    else
      render 'cars/show', status: :unprocessable_entity
    end
  end

  def destroy
    @favourite = Favourite.find(params[:id])
    @favourite.destroy
    redirect_to favourites_path, status: :see_other

  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def landing

  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @review = Review.new(review_params)
    @car = Car.find(params[:car_id])
    @review.car = @car
    if @review.save
      redirect_to car_path(@car)
    else
      @favourite = Favourite.new

      render 'cars/show', status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cars/index.html.erb
<%= render 'shared/navbar' %>

<h1>List of all cars</h1>

<div class="cards-index">
  <% @cars.each do |car| %>
    <%= link_to car_path(car) do %>
        <h2><%= car.model %></h2>
        <%= image_tag car.image_url %>
      </div>
    <% end %>
  <% end %>

app/views/cars/show.html.erb
<%= render 'shared/navbar' %>


<h1><%= @car.model %></h1>
<p><%= @car.brand %></p>
<p><%= @car.year %></p>
<p><%= @car.fuel %></p>
<p><%= image_tag @car.image_url %></p>


<hr>
<% if @car.favourites.empty? %>
  <h2>Add car to favourites</h2>
  <%= simple_form_for [@car, @favourite] do |f| %>
    <%= f.submit 'Add to my garage' %>
  <% end %>
<% else %>
  <p>This is already in your garage</p>
<% end %>

<hr>
<h2>Add a review</h2>
<%= simple_form_for [@car, @review] do |f| %>
  <%= f.input :comment %>
  <%= f.input :rating, collection: 0..5 %>
  <%= f.submit %>
<% end %>

<hr>
<% @car.reviews.each do |review| %>
<p>Comment: <%= review.comment %> | Rating: <%= review.rating %></p>
<% end %>

app/views/favourites/index.html.erb
<%= render 'shared/navbar' %>

<h1>My garage</h1>
<% @favourites.each do |favourite| %>
  <p><%= favourite.car.brand %></p>
  <p><%= favourite.car.model %></p>
  <%= link_to 'delete', favourite_path(favourite),
  data: {turbo_method: :delete,
        turbo_confirm: "Are you sure you want to delete #{favourite.car.model}?"
        }
  %>
  <hr>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAwesomeGarage</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <%= yield %>
  </body>
</html>

app/views/pages/landing.html.erb
<h1>welcome to the awesome garage</h1>
<%= link_to "Enter", cars_path %>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <%= image_tag "" %>
  <div>
  my awesome garage
  <%= link_to "home", cars_path %>
  <%= link_to "my garage", favourites_path %>
  </div>
</div>